repos:
  - repo: local
    hooks:
      - id: lint
        name: Lint
        language: system
        pass_filenames: false
        entry: poetry run task lint

      - id: format
        name: Format
        language: system
        pass_filenames: false
        entry: poetry run task format

      - id: analyze
        name: Analyze
        language: system
        pass_filenames: false
        entry: poetry run task analyze